# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20170309_1409'),
        ('Nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('id_db', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EntradaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('DB', 'Debito'), ('CR', 'Credito')], max_length=5)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.AsientoContable')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='monto',
        ),
        migrations.AddField(
            model_name='tipo',
            name='defecto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipo',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tipo',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entradacontable',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.Transaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='pago',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Nomina.Pago'),
        ),
    ]
