# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0003_auto_20170406_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
