# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0005_auto_20170406_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
