# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.TextField(max_length=20)),
                ('primer_nombre', models.TextField(max_length=150)),
                ('segundo_nombre', models.TextField(max_length=150)),
                ('primer_apellido', models.TextField(max_length=150)),
                ('segundo_apellido', models.TextField(max_length=150)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
