# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='primer_apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='primer_nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_nombre',
            field=models.CharField(max_length=150),
        ),
    ]
